.TH Motherbee 1 "2023-01-14" 0.1.0 "Docker swarm organization, maintenance, upkeep & deployment tool"
.SH "NAME"
mob
\- docker swarm management tool

.SH "SYNOPSIS"
.B mob
[OPTIONS]
COMMANDS
[ARGS]

.SH DESCRIPTION
mob (Motherbee) is an docker & docker swarm tool that organizes, maintains and aids in the management of the docker environment.
The intention is to aid in maintaining and revising one codebase for multi

